
services:
  dbmaster2:
    image: allbano/pg16master
    container_name: dbmaster
    volumes:
      - ./db/master:/var/lib/postgresql/data
      - ./db/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./db/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - type: tmpfs
        target: /dev/shm
    hostname: dbmaster
    ports:
      - target: 5432
        published: 55532
        protocol: tcp
        mode: host
    environment:
      - PGDATA=/var/lib/postgresql/data

